### ISSUE TITLE
I fear I'm doing something stupid...

### ISSUE THREAD

**Issue by domesticmouse** [pylaligand/dart-sqlite#55]
My `pubspec.yaml` looks like this:

    name: sqlite_test
    version: 0.0.1
    description: A simple console application.
    dependencies:
      sqlite: ^0.3.0

My `main.dart` looks like this:

    import 'package:sqlite/sqlite.dart';

    main(List<String> args) async {
      final db = new Database.inMemory();

      Row row =
          await db.query('SELECT ?+16, UPPER(?)', params: [2000, 'Ligue 1']).first;
      final int year = row[0];
      final String league = row[1];
      print('-- $league $year --');
    }

And yet, running it fails like this:

    $ pub run bin/main.dart
    Unhandled exception:
    Class 'Database' has no instance method 'query'.

    NoSuchMethodError: method not found: 'query'
    Receiver: Instance of 'Database'
    Arguments: ["SELECT ?+16, UPPER(?)", params: Instance(length:2) of '_GrowableList']
    #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
    #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
    #2      main.<main_async_body> (file:///Users/brett/dart-projects/sqlite-test/bin/main.dart:7:16)
    #3      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
    #4      _microtaskLoop (dart:async/schedule_microtask.dart:41)
    #5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
    #6      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
    #7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Halp?

**Comment by pylaligand** [comment]
Have you run `pub get`? What version of the library do you see when running `pub deps`?

**Comment by domesticmouse** [comment]
As you have probably guessed, I was on v0.3.0 and was getting confused due to the API change. When I upgraded to v0.4.0 all the problems magically went away. Sorry, I should have mentioned that. 

Thanks!

**Comment by pylaligand** [comment]
Glad it is now working!
